.ig
Copyright (c) 2012, Comfirm AB
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 
    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.
    * Neither the name of the Comfirm AB nor the names of its contributors
      may be used to endorse or promote products derived from this software
      without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR NY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
..
.
.de TQ
.  br
.  ns
.  TP \\$1
..
.
.
.TH HBEATD 7 "14 September 2012" "Hbeatd Version 1.3.1"
.
.
.\" -----------------------------------------------------------------
.
.SH NAME
.
.B hbeatd
\-\- a simple and lightweight heartbeat sensor and pulse program
.
.
.\" -----------------------------------------------------------------
.
.SH SYNOPSIS
.
.B hbeatd
[
.IR options .\|.\|.\&
]
.br
.B hbeatd
[
.B -pv\&
]
[
.B -d\&
.I ip
]
[
.B -P\&
.I port
]
[
.B -i\&
.I interval
]
[
.B -g\&
.I group
]
.br
.B hbeatd
[
.B -sv\&
]
[
.B -P\&
.I port
]
[
.B -t\&
.I tolerance
]
.
.
.\" -----------------------------------------------------------------
.
.SH DESCRIPTION
.
.
.B hbeatd
is a simple and lightweight program for sending and receiving
heartbeats that can be used to check the status of nodes in a cluster
of servers. The pulse program on the nodes sends udp packages to
chosen sensor. The sensor collects the ip's along with the server
group and builds a list. Everytime a new heartbeat is received it
will update the timestamp for the node and check the list for dead
nodes (nodes with a timestamp older than the tolerance level). If a
node is dead, a script located at /etc/hbeatd/rc.d will run.
.
.\" -----------------------------------------------------------------
.
.SH OPTIONS
.
Unless specifically stated otherwise, options are applicable in all operating modes.
.TP
.B \-p
Run
.B hbeatd
in pulse mode.
.
.TP
.B \-s
Run
.B hbeatd
in sensor mode.
.
.TP
.B \-v
Run in verbose mode, not as daemon.
.
.TP
.BI \-d ip
Destination ip address (only available in pulse mode).
The default is 127.0.0.1.
.
.TP
.BI \-P port
Destination port number (only available in pulse mode).
The default is 6220.
.
.TP
.BI \-i interval
The interval in milliseconds between pulses (only available in pulse mode).
The default is 1000 (1 second).
.
.TP
.BI \-g group
A group name ex. 'web' or 'db', good when building lists of available nodes for deployment and maintenance etc. (only available in pulse mode).
The default is 'misc'.
.
.TP
.BI \-t tolerance
The number of seconds before reporting that the node is dead (only available in sensor mode).
.
The default is 4.
.
.
.SH "EXAMPLES"
.
.TP
hbeat -d 192.168.0.50
Start
.B hbeatd
in pulse mode.
.
.TP
hbeatd -p -i 800 -v
Start
.B hbeatd
in pulse mode without daemonizing it. Sending heartbeats with 800 milliseconds interval.
.
.TP
hbeatd -s
Start
.B hbeatd
in sensor mode.
.
.TP
hbeatd -s -t 20
Start 
.B hbeatd
in sensor mode with a tolereance of 20 seconds.
.
.TP
hbeatd -s -P 8910 -v
Start
.B hbeatd
in sensor mode on port 8910 without daemonizing it (good for debugging).
.
.\" -----------------------------------------------------------------
.
.SH FILES
.TP
.B /etc/hbeatd/rc.d
An executable file that runs everytime
.B hbeatd
founds a new, dead or resurrected node.
.
The script or program can take three arguments; status, ip and group.
.
.br
.B Example sh-script:

if [ "$1" = "dead" ]; then
.br
	echo "dead: $2($3)" >> /tmp/hbeatd.log
.br
elif [ "$1" = "up" ]; then
.br
	echo "up: $2($3)" >> /tmp/hbeatd.log
.br
elif [ "$1" = "new" ]; then
.br
	echo "new: $2($3)" >> /tmp/hbeatd.log
.br
fi
.
.\" -----------------------------------------------------------------
.
.SH AUTHOR
.
Jack Engqvist Johansson <jack.johansson@comfirm.se>
.
.\" Local Variables:
.\" mode: nroff
.\" End:
